# Generated by Django 3.2.6 on 2021-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
